name: ar_location_viewer_example
description: Demonstrates how to use the ar_location_viewer plugin.

publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  ar_location_viewer:
    path: ../

  cupertino_icons: ^1.0.2
  geolocator: ^10.1.0
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
