name: ar_location_viewer
description: ArLocationViewer is designed to used in areas with large concentration of static POIs
# pub.dev using `flutter pub publish`.
version: 2.0.10
homepage: 'https://github.com/dariocavada/ar_location_viewer.git'

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.7
  sensors_plus: ^4.0.2
  camera: ^0.10.5
  permission_handler: ^11.1.0
  vector_math: ^2.1.4
  geolocator: ^10.1.0
  native_device_orientation: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  plugin:
    platforms:
      android:
        package: com.pie.technology.ar.location.view.ar_location_viewer
        pluginClass: ArLocationViewerPlugin
      ios:
        pluginClass: ArLocationViewerPlugin
